// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6szWcDby7GyXwL3q2gjZDn-kipQzIWfE',
    appId: '1:1049069243514:web:dacb7bb42e4391eb28ffc3',
    messagingSenderId: '1049069243514',
    projectId: 'vividcanvas-7a118',
    authDomain: 'vividcanvas-7a118.firebaseapp.com',
    storageBucket: 'vividcanvas-7a118.firebasestorage.app',
    measurementId: 'G-GJQWGSRYWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANQIRgejPXoLjQ-OGOkdykD8C8rFAdzrw',
    appId: '1:1049069243514:android:117f023ea266eaf528ffc3',
    messagingSenderId: '1049069243514',
    projectId: 'vividcanvas-7a118',
    storageBucket: 'vividcanvas-7a118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAqdklVg-Qq9L_otcHQB9HYNnRNlwG4Tc',
    appId: '1:1049069243514:ios:e00aca476b0dad0528ffc3',
    messagingSenderId: '1049069243514',
    projectId: 'vividcanvas-7a118',
    storageBucket: 'vividcanvas-7a118.firebasestorage.app',
    iosBundleId: 'com.maryamabdallahhh.vividCanvas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAqdklVg-Qq9L_otcHQB9HYNnRNlwG4Tc',
    appId: '1:1049069243514:ios:e00aca476b0dad0528ffc3',
    messagingSenderId: '1049069243514',
    projectId: 'vividcanvas-7a118',
    storageBucket: 'vividcanvas-7a118.firebasestorage.app',
    iosBundleId: 'com.maryamabdallahhh.vividCanvas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6szWcDby7GyXwL3q2gjZDn-kipQzIWfE',
    appId: '1:1049069243514:web:cbc111921c51069928ffc3',
    messagingSenderId: '1049069243514',
    projectId: 'vividcanvas-7a118',
    authDomain: 'vividcanvas-7a118.firebaseapp.com',
    storageBucket: 'vividcanvas-7a118.firebasestorage.app',
    measurementId: 'G-9C79Y6Z3H6',
  );
}
